name: Dependency Updates

on:
  schedule:
    # Run weekly on Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Update Dependencies
        run: |
          pnpm update --latest --recursive
          
          echo "## 📦 Dependency Update Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          git diff package.json pnpm-lock.yaml >> $GITHUB_STEP_SUMMARY || echo "No changes" >> $GITHUB_STEP_SUMMARY

      - name: Run Tests
        run: |
          pnpm install --frozen-lockfile
          pnpm build
          pnpm test

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: update dependencies'
          body: |
            ## 📦 Dependency Updates
            
            This PR updates all dependencies to their latest versions.
            
            ### Changes
            - Updated all packages to latest versions
            - All tests passing
            
            Please review the changes and merge if everything looks good.
          branch: chore/update-dependencies
          delete-branch: true
          labels: dependencies, automated

  renovate:
    name: Renovate Bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: debug

  security-updates:
    name: Security Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Check for Security Vulnerabilities
        run: |
          pnpm audit --json > audit-report.json || true
          
          echo "## 🔒 Security Audit" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ -s audit-report.json ]; then
            echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
            cat audit-report.json >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "✅ No security vulnerabilities found" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Auto-fix Security Issues
        run: |
          pnpm audit fix || true

      - name: Create Security Update PR
        if: success()
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'fix: security vulnerability updates'
          title: '🔒 fix: security vulnerability updates'
          body: |
            ## 🔒 Security Vulnerability Updates
            
            This PR automatically fixes security vulnerabilities found in dependencies.
            
            ### Changes
            - Updated vulnerable packages
            - All security issues resolved
            
            **Priority**: High - Please review and merge as soon as possible.
          branch: security/auto-fix
          delete-branch: true
          labels: security, dependencies, automated

  check-outdated:
    name: Check Outdated Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Outdated Packages
        run: |
          echo "## 📊 Outdated Packages Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          pnpm outdated --recursive > outdated.txt || true
          
          if [ -s outdated.txt ]; then
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            cat outdated.txt >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "✅ All packages are up to date" >> $GITHUB_STEP_SUMMARY
          fi
